// src/components/SwapCertified.vue

<template>
  <v-container>
    <v-row>
      <v-col cols="11" class="mx-auto">
        <!-- Title & Subtitle -->
        <title-subtitle :title="title" :subtitle="subtitle" :separed2="true"></title-subtitle>

        <!-- Swap Title -->
        <v-row>
          <v-col cols="12" class="text-center pt-2">
            <span class="font-weight-regular fs-1-2rem">Swap Certificate:</span>
          </v-col>
        </v-row>

        <v-row>
          <v-col cols="12" md="10" lg="8" class="mx-auto border-gray-5px pt-0 pb-0">
            <v-row>
              <v-col cols="12" sm="8" md="7" lg="8" class="mx-auto pa-5 pb-0">
                <v-row>
                  <!-- Sirius Account -->
                  <v-col cols="12" class="w-w-b-w word-break-all pt-0">
                    <span class="fs-08rem font-weight-bold">
                      Sirius Account:
                      <br />
                    </span>
                    <span class="fs-09rem">{{certified.siriusAddres}}</span>
                  </v-col>
                  <!-- Nis1 timestamp -->
                  <v-col cols="12" class="w-w-b-w word-break-all pt-0">
                    <span class="fs-08rem font-weight-bold">NIS1 Timestamp:&nbsp;</span>
                    <span class="fs-09rem">{{certified.nis1Timestamp}}</span>
                  </v-col>
                  <!-- Nis1 public key -->
                  <v-col cols="12" class="w-w-b-w word-break-all pt-0">
                    <span class="fs-08rem font-weight-bold">
                      NIS1 Public Key:
                      <br />
                    </span>
                    <span
                      class="fs-09rem"
                    >{{certified.nis1PublicKey}}</span>
                  </v-col>
                  <!-- QR & Hash -->
                  <v-col cols="12 pb-0">
                    <v-row>
                      <!-- QR -->
                      <v-col cols="6" md="6" lg="5" class="pt-0 pb-0">
                        <vue-qr
                          :logoSrc="require(`@/assets/${logo}`)"
                          :text="`${urlExplorer}${certified.nis1TransactionHash}`"
                          :size="150"
                          :dotScale="0.5"
                          :correctLevel="1"
                          :margin="0"
                          :callback="qrBase64"
                        ></vue-qr>
                      </v-col>
                      <!-- Hash -->
                      <v-col cols="6" md="6" lg="7" class="w-w-b-w word-break-all pt-0 pb-0">
                        <span class="fs-08rem font-weight-bold">
                          NIS1 Transation Hash:
                          <br />
                        </span>
                        <span class="fs-09rem primary--text cursor-pointer">
                          <a
                            class="text-d-none"
                            :href="`${urlExplorer}${certified.nis1TransactionHash}`"
                            target="_blank"
                          >{{certified.nis1TransactionHash}}</a>
                        </span>
                      </v-col>
                      <!-- Swap Note -->
                      <v-col cols="12" class="pt-2 pb-0">
                        <p class="fs-08rem"><b>Note: </b> The Swap Process may take a few hours to complete.</p>
                      </v-col>
                    </v-row>
                  </v-col>
                </v-row>
              </v-col>
              <!-- Badge -->
              <v-col cols="12" sm="4" md="5" lg="4" class="background-blue-gradient d-flex align-center justify-center mx-auto">
                <v-img :src="require(`@/assets/img/${badge}`)" max-width="150" max-height="150"></v-img>
              </v-col>
            </v-row>
          </v-col>
        </v-row>

        <!-- Warning Message -->
        <v-row>
          <v-col cols="12" md="10" lg="8" class="mx-auto mt-8">
            <v-alert outlined type="warning" prominent class="text-center line-h-1-02em" dense>
              <span class="gray-black--text caption">{{warningText}}</span>
            </v-alert>
          </v-col>
        </v-row>

        <!-- Checkbox -->
        <v-row>
          <v-col cols="12" md="10" lg="8" class="mx-auto d-flex align-center justify-center pb-0">
            <v-checkbox v-model="confirmSwap" :label="`I confirm that I have saved a copy of my certificate.`"></v-checkbox>
          </v-col>
        </v-row>

        <!-- Buttons -->
        <custom-buttons class="mt-4" @action="action" :arrayBtn="arrayBtn"></custom-buttons>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import VueQr from 'vue-qr'

export default {
  props: ['certified'],
  beforeMount () {
    this.urlExplorer = this.$store.getters['swapStore/configNIS1'].urlExplorer
  },
  data: () => {
    return {
      arrayBtn: {
        save: {
          key: 'save',
          action: 'save',
          disabled: false,
          color: 'primary',
          loading: false,
          text: 'Save'
        },
        continue: {
          key: 'continue',
          action: 'continue',
          disabled: true,
          color: 'primary',
          loading: false,
          text: 'Continue'
        }
      },
      badge: 'badge-silver-proximax-sirius-wallet.svg',
      base64QR: '',
      confirmSwap: false,
      urlExplorer: '',
      logo: 'ProximaX-Favicon.png',
      subtitle: 'The Swap Process has already started.',
      title: 'Congratulations!',
      warningText: 'Save a copy of your certificate. It is needed in the event of an error.'
    }
  },
  methods: {
    action (action) {
      switch (action) {
        case 'continue':
          this.$router.push('/').catch(e => {})
          break
        case 'save':
          const param = {
            qr: this.base64QR,
            address: this.certified.siriusAddres,
            timestamp: this.certified.nis1Timestamp,
            publicKey: this.certified.nis1PublicKey,
            hash: this.certified.nis1TransactionHash
          }

          const pdf = this.$pdfGenerator.swapCertified(param)
          pdf.save(`${this.certified.nis1TransactionHash}_swap_certified`)
          break
      }
    },
    qrBase64 (base64) {
      this.base64QR = base64
    }
  },
  watch: {
    confirmSwap: function () {
      const arrayBtn = this.arrayBtn
      arrayBtn.continue.disabled = !this.confirmSwap
    }
  },
  components: {
    VueQr,
    'title-subtitle': () => import('@/components/shared/Title'),
    'custom-buttons': () => import('@/components/shared/Buttons')
  }
}
</script>

<style>
.v-alert--outlined {
  border: 3px solid currentColor !important;
}
</style>

// src/app/swap/views/swap-certified/swap-certified.component.ts
import { Component, OnInit, Input } from '@angular/core';
import * as jsPDF from 'jspdf';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-swap-certified',
  templateUrl: './swap-certified.component.html',
  styleUrls: ['./swap-certified.component.css']
})
export class SwapCertifiedComponent implements OnInit {

  @Input() params: any;
  checked: boolean = false;
  explorerUrl = `${environment.nis1.urlExplorer}`;



  img: any;
  address: any;
  timestamp: any;
  publicKey: any;
  transactionHash: any;

  constructor() { }

  ngOnInit() {
  }


  /**
   *
   *
   * @memberof SwapCertifiedComponent
   */
  goToNemExplorer() {
    window.open(this.explorerUrl);
  }

  goToRoute() {

  }

  printCertificate() {
    let doc = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [800, 475]
    });

    doc.addImage(this.img, 'JPEG', 0, 0, 600, 360);
    doc.setFontSize(24);
    doc.setTextColor('#000000');
    doc.text('Swap Certificate', 30, 50);
    doc.line(30, 60, 300, 60, 'S');

    doc.setFontSize(14);
    doc.setFontType('bold');
    doc.text('Sirius Account:', 30, 90);
    doc.setFontType('normal');
    doc.text(this.address, 30, 105);

    doc.setFontSize(14);
    doc.setFontType('bold');
    doc.text('NIS1 Timestamp:', 30, 130);
    doc.setFontType('normal');
    doc.text(this.timestamp, 130, 131);

    doc.setFontSize(14);
    doc.setFontType('bold');
    doc.text('NIS1 Public Key:', 30, 155);
    doc.setFontType('normal');
    doc.text(this.publicKey, 30, 170, { maxWidth: 370 });

    doc.addImage(this.qrCreate(), 'jpg', 30, 210, 100, 100);

    doc.setFontType('bold');
    doc.text('NIS1 Transaction Hash:', 140, 230);
    doc.setFontType('normal');
    doc.text(this.transactionHash, 140, 245, { maxWidth: 280 });

    doc.text('Note: the swap process may take a several hours to complete.', 30, 330);

    doc.save('Swap_Certificate.pdf');
  }

}

<div class="container mb-2rem animated fadeIn">
  <!-- CERTIFICATE -->
  <div class="row">
    <div class="col-11 col-md-10 col-lg-9 col-xl-8 mx-auto mt-3rem">
      <div class="row">
        <div class="col-12 txt-a-center">
          <span class="fs-1-7rem fw-600 txt-a-center line-h-1-2em color-blue-intermedio">Congratulations!</span> <br>
          <span>The Swap Process has already started.</span>
        </div>

        <div class="col-11 col-md-10 mx-auto">
          <hr class="mt-05rem mb-06rem">
        </div>
      </div>

      <div class="row mt-1rem">
        <div class="col-12 d-flex justify-content-center mx-auto">
          <span class="fs-1-2rem">Swap Certificate:</span>
        </div>
      </div>

      <div class="row audit-front mt-05rem mx-auto">
        <div class="col-12 col-lg-8 background-white">
          <div class="row p-1rem">
            <div class="col-12 mb-1rem d-flex flex-column">
              <span class="w-b-w fs-08rem"><b class="fw-bold">Sirius Account: </b></span>
              <!-- <span class="fs-09rem">{{ address }}</span> -->
            </div>
            <div class="col-12 mb-1rem">
              <!-- <span class="word-break-all fs-08rem"><b class="fw-bold">NIS1 Timestamp: </b>{{ timestamp }}</span> -->
            </div>
            <div class="col-12 mb-1rem w-w-b-w word-break-all">
              <span class="w-b-w fs-08rem"><b class="fw-bold">NIS1 Public Key: </b></span>
              <!-- <span class="fs-09rem">{{ publicKey }}</span> -->
            </div>
            <div class="row">
              <div class="col-12 col-md-4 txt-a-center">
                <img [src]="qrSrc" alt="qrCode">
              </div>
              <div class="col-12 col-md-8 w-w-b-w word-break-all d-flex flex-column">
                <span class="w-b-w fs-08rem">
                  <b class="fw-bold">NIS1 Transation Hash: </b>
                </span>
                <!-- <span class="text-cl-m cursor-p fs-09rem" (click)="goToNemExplorer()">{{ transactionHash }}</span> -->
              </div>
            </div>
            <div class="col-12 w-b-w fs-08rem">
              <b class="fw-bold">Note:</b>
              <span class="fs-09rem"> The Swap Process may take a few hours to complete.</span>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-4 d-flex justify-content-center align-items-center background-blue-gradient">
          <figure class="p-05rem row mar-1rem">
            <img src="assets/images/img/badge-silver-proximax-sirius-wallet.svg" alt="Medal" width="150">
          </figure>
        </div>
      </div>
    </div>
  </div>
  <!-- END CERTIFICATE -->

  <!-- WARNING -->
  <div class="row mt-2rem">
    <div class="col-md-10 col-lg-8 col-xl-8 mx-auto box-transparent-border-orange">
      <div class="txt-a-center">
        <img src="assets/images/img/icon-transaction-unconfirmed-white.svg" style="filter: invert(50%)" alt=""
          width="30">
      </div>
      <p class="fs-08rem txt-a-center mt-05rem mb-0 lh-1-1em">
        Save a copy of your certificate. It is needed in the event of an error.
      </p>
    </div>
  </div>
  <!-- END WARNING -->

  <div class="row mt-1rem">
    <div class="col-11 col-sm-10 col-lg-9 col-xl-8 mx-auto txt-a-center">
      <mdb-checkbox [(ngModel)]="checked" [checked]="checked"> I confirm that I have saved a copy of my certificate.
      </mdb-checkbox>
    </div>
  </div>

  <!-- BUTTON -->
  <div class="row mt-1rem">
    <div class="col-12 col-sm-6 d-flex justify-content-center justify-content-sm-end">
      <button mdbBtn type="button" rounded="true" mdbWavesEffect class="btn-proximax" size="md"
        (click)="printCertificate()">
        <span class="color-white">Save</span>
      </button>
    </div>

    <div class="col-12 col-sm-6 d-flex justify-content-center justify-content-sm-start">
      <button mdbBtn rounded="true" mdbWavesEffect (click)="goToRoute()" [disabled]="!checked" class="btn-proximax"
        size="md">
        <span class="color-white">Continue</span>
      </button>
    </div>
  </div>
  <!-- END BUTTON -->

</div>
