// src/components/wallet/WalletCreated.vue

<template>
  <v-container>
    <v-row>
      <v-col cols="11" class="mx-auto">
        <!-- Title & Subtitle -->
        <title-subtitle :title="title" :subtitle="subtitle" :separed2="true"></title-subtitle>

        <v-row>
          <!-- Wallet name -->
          <v-col cols="12" class="pt-0 text-center headline font-weight-regular">
            <span>{{walletName}}</span>
          </v-col>

          <v-col cols="12" sm="10" md="9" lg="8" class="mx-auto">
            <v-row>
              <!-- Address -->
              <v-col cols="12" class="box-gray mb-3">
                <v-row class="d-flex align-center">
                  <v-col cols="10" class="pt-0 pb-0 overflow-ellipsis-nowrap mx-auto">
                    <span class="body-1 font-weight-medium">
                      Address:
                      <br />
                    </span>
                    <span class="body-2">{{address}}</span>
                  </v-col>

                  <!-- Icon -->
                  <v-col cols="2" class="pt-0 pb-0 text-right">
                    <v-btn
                      text
                      icon
                      @click="doCopy('Address', address)"
                    >
                      <v-icon>mdi-content-copy</v-icon>
                    </v-btn>
                  </v-col>
                </v-row>
              </v-col>

              <!-- Warning Message -->
              <v-col cols="12">
                <v-alert outlined type="warning" prominent class="text-center line-h-1-02em" dense>
                  <span class="gray-black--text caption">
                    Make sure you store your private key in a safe place.
                    <br />Access to your digital assets cannot be recovered without it.
                  </span>
                </v-alert>
              </v-col>

              <!-- Private Key -->
              <v-col cols="12" class="box-gray mb-5" v-if="showPrivateKey">
                <v-row class="d-flex align-center">
                  <v-col cols="10" class="pt-0 pb-0 overflow-ellipsis-nowrap mx-auto">
                    <span class="body-1 font-weight-medium">
                      Private Key:
                      <br />
                    </span>
                    <span class="body-2 d-flex">{{privateKey}}</span>
                  </v-col>

                  <!-- Icon -->
                  <v-col cols="2" class="pt-0 pb-0 text-right">
                    <v-btn
                      text
                      icon
                      @click="doCopy('Private Key', privateKey)"
                    >
                      <v-icon>mdi-content-copy</v-icon>
                    </v-btn>
                  </v-col>
                </v-row>
              </v-col>
            </v-row>

            <!-- Buttons -->
            <custom-buttons @action="action" :arrayBtn="buttons"></custom-buttons>
          </v-col>
        </v-row>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { mapMutations } from 'vuex'
import generalMixins from '../../mixins/general-mixin'
import swapMixin from '../../mixins/swap-mixin'

export default {
  mixins: [generalMixins, swapMixin],
  props: ['walletInfo'],
  data: () => {
    return {
      address: '',
      arrayBtn: {
        showPvk: {
          key: 'showPvk',
          action: 'showPrivateKey',
          disabled: false,
          color: 'primary',
          loading: false,
          text: 'Show Private Key'
        },
        savePaperWallet: {
          key: 'showPvk',
          action: 'savePaperWallet',
          disabled: false,
          color: 'primary',
          loading: false,
          text: 'Save Paper Wallet'
        },
        continue: {
          key: 'continue',
          action: 'continue',
          disabled: false,
          color: 'primary',
          loading: false,
          text: 'Continue'
        }
      },
      infoOwnedSwap: null,
      privateKey: '',
      subtitle: 'Your wallet has been successfully created.',
      showPrivateKey: false,
      title: 'Congratulations!',
      walletName: ''
    }
  },
  components: {
    'title-subtitle': () => import('@/components/shared/Title'),
    'custom-buttons': () => import('@/components/shared/Buttons')
  },
  methods: {
    ...mapMutations('swapStore', ['SET_SWAP_DATA']),
    async initSwap (publicKey, accountName, walletName) {
      this.arrayBtn.continue.disabled = true
      this.arrayBtn.continue.loading = true
      // Search Info Swap
      const info = await this.searchSwapInfo(publicKey, accountName, walletName)
      this.infoOwnedSwap = info.mosaicInfoOwnedSwap
      this.arrayBtn.continue.disabled = false
      this.arrayBtn.continue.loading = false
    },
    action (action) {
      switch (action) {
        case 'showPrivateKey':
          this.showPrivateKey = !this.showPrivateKey
          break
        case 'savePaperWallet':
          console.log('savePaperWallet')
          break
        case 'continue':
          if (this.infoOwnedSwap) {
            this.SET_SWAP_DATA(this.infoOwnedSwap)
            this.$router.push('/swap-account-nis1-found').catch(e => {})
          } else {
            this.$router.push('/').catch(e => {})
          }
          break
      }
    },
    enableDisableBtn (status) {
      this.arrayBtn.continue.disabled = status
      this.arrayBtn.continue.loading = status
    }
  },
  computed: {
    buttons () {
      const arrayBtn = this.arrayBtn
      arrayBtn['showPvk'].text = (this.showPrivateKey) ? 'Hide Private Key' : 'Show Private Key'
      return arrayBtn
    }
  },
  beforeMount () {
    const walletInfo = this.walletInfo.data
    this.address = walletInfo.accounts[0].address.pretty()
    this.walletName = walletInfo.name
    this.pvk = this.walletInfo.pvk.toUpperCase()
    if (walletInfo.accounts[0].nis1Account) {
      const publicKey = walletInfo.accounts[0].nis1Account.publicKey
      const accountName = walletInfo.accounts[0].name
      this.SET_SWAP_DATA(null)
      this.initSwap(publicKey, accountName, this.walletName)
    }
  }
}
</script>

<style>
.v-alert--outlined {
    border: 3px solid currentColor !important;
}
</style>

// src/app/wallet/views/wallet-created/wallet-created.component.ts
import { Component, OnInit } from '@angular/core';
import { SimpleWallet } from 'tsjs-xpx-chain-sdk';
import { Router } from '@angular/router';
import { WalletService, AccountsInterface } from '../../services/wallet.service';
import { ProximaxProvider } from '../../../shared/services/proximax.provider';
import { AppConfig } from '../../../config/app.config';
import { SharedService } from '../../../shared/services/shared.service';

@Component({
  selector: 'app-wallet-created',
  templateUrl: './wallet-created.component.html',
  styleUrls: ['./wallet-created.component.css']
})
export class WalletCreatedComponent implements OnInit {

  address = '';
  description = 'Warning! Before proceeding, make sure store your private key in a safe place. Access to your digital assets cannot be recovered without it.';
  publicKey = '';
  privateKey = '';
  title = 'Congratulations';
  titleDescription = 'Your wallet has been successfully created';
  subtitle = '';
  viewPrivateKey = false;
  routeAuth = `/${AppConfig.routes.auth}`;
  walletData: {
    data: any,
    dataAccount: AccountsInterface;
    wallet: SimpleWallet
  } = null;

  constructor(
    private walletService: WalletService,
    private proximaxProvider: ProximaxProvider,
    private sharedService: SharedService,
    private router: Router
  ) { }

  ngOnInit() {
    this.walletData = this.walletService.accountWalletCreated;
    if (this.walletData !== null) {
      this.subtitle = this.walletData.data.name;
      this.address = this.walletData.wallet.address.pretty();
      this.privateKey = this.proximaxProvider.decryptPrivateKey(
        this.walletData.data.algo, this.walletData.dataAccount.encrypted, this.walletData.dataAccount.iv
      ).toUpperCase();
      this.publicKey = this.proximaxProvider.getPublicAccountFromPrivateKey(this.privateKey, this.walletData.data.network).publicKey;
      this.walletData = null;
      this.walletService.accountWalletCreated = null;
    }else {
      this.router.navigate([`/${AppConfig.routes.home}`]);
    }
  }

  ngOnDestroy(): void {
    this.walletData = null;
    this.walletService.accountWalletCreated = null;
  }

  /**
   *
   *
   * @param {string} message
   * @memberof WalletCreatedComponent
   */
  copyMessage(message: string) {
    this.sharedService.showSuccess('', `${message} copied`);
  }

  /**
   * 
   */
  goToRoute() {
    // [routerLink]="[routes.backToService]"
    const nis1Info = this.walletService.getAccountInfoNis1();
    console.log('this a nis1 Info ------>', nis1Info);
    if (nis1Info.nis1Account && nis1Info.nis1Account !== null) {
      this.router.navigate([`/${AppConfig.routes.walletNis1Found}`]);
    } else {
      this.router.navigate([this.routeAuth]);
    }
  }
}

<div class="container mt-3rem mb-2rem animated fadeIn">
  <div class="row">
    <div class="col-11 mx-auto txt-a-center">
      <span class="fs-1-7rem fw-600 txt-a-center line-h-1-2em color-blue-intermedio">{{title}}</span>
    </div>
    <div class="col-11 mx-auto txt-a-center">
      <span class="txt-a-center fs-1rem line-h-1-2em">{{titleDescription}}</span>
    </div>
    <div class="col-11 col-md-10 mx-auto">
      <hr class="mt-05rem mb-06rem">
    </div>
    <div class="col-11 mx-auto txt-a-center mt-05rem mb-05rem">
      <span class="fs-1-7rem txt-a-center line-h-1-2em fw-400">{{subTitle}}</span>
    </div>
  </div>
  <!-- address -->
  <div class="row">
    <div class="col-11 col-sm-12 col-md-10 col-lg-8 mx-auto d-flex align-items-center box-grey">
      <div class="col-10">
        <span class="fw-bold">Address: </span><br>
        <span class="font-small d-flex">{{walletData.wallet.address.pretty()}}</span>
      </div>
      <div class="col-2 text-right">
        <img src="assets/images/img/icon-copy-clipboard-gray-proximax-sirius-wallet.svg" class="cursor-p" alt="Copy"
          width="20" (click)="copyMessage('Address')" ngxClipboard [cbContent]="address">
      </div>
    </div>
  </div>

  <!-- Public key -->
  <div class="row" v-if="walletData?.dataAccount?.publicAccount?.publicKey">
    <div class="col-11 col-sm-12 col-md-10 col-lg-8 mx-auto d-flex align-items-center box-grey">
      <div class="col-10">
        <span class="fw-bold">Public key: </span><br>
        <span class="font-small d-flex">{{walletData.dataAccount.publicAccount.publicKey}}</span>
      </div>
      <div class="col-2 text-right">
        <img src="assets/images/img/icon-copy-clipboard-gray-proximax-sirius-wallet.svg" class="cursor-p" alt="Copy"
          width="20" (click)="copyMessage('Address')" ngxClipboard [cbContent]="address">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-11 col-sm-12 col-md-10 col-lg-8 mb-1rem mx-auto box-transparent-border-orange">
      <div class="txt-a-center">
        <img src="assets/images/img/icon-transaction-unconfirmed-white.svg" style="filter: invert(50%)" alt="" width="30">
      </div>
      <h6 class="fw-600"></h6>
      <p class="fs-08rem txt-a-center mt-05rem mb-0 lh-1-1em">
        Make sure you store your private key in a safe place.<br>
        Access to your digital assets cannot be recovered without it.
      </p>
    </div>
  </div>
  <!-- private key -->
  <ng-container *ngIf="viewPrivateKey">
    <div class="row animated fadeIn">
      <div class="col-11 col-sm-12 col-md-10 col-lg-8 mx-auto d-flex align-items-center box-grey">
        <div class="col-10">
          <span class="fw-bold">Private Key: </span><br>
          <span class="font-small d-flex">{{ privateKey }}</span>
        </div>
        <div class="col-2 text-right">
          <img src="assets/images/img/icon-copy-clipboard-gray-proximax-sirius-wallet.svg" class="cursor-p" alt="Copy"
            width="20" (click)="copyMessage('Private Key')" ngxClipboard [cbContent]="privateKey">
        </div>
      </div>
    </div>
  </ng-container>

  <!-- buttons create and clear -->
  <div class="row mt-2rem d-flex justify-content-center">
    <button mdbBtn type="button" rounded="true" mdbWavesEffect class="btn-proximax" size="md"
      (click)="viewPrivateKey = !viewPrivateKey">
      <span class="color-white" *ngIf="viewPrivateKey">Hide Private Key</span>
      <span class="color-white" *ngIf="!viewPrivateKey">Show Private Key</span>
    </button>

    <button mdbBtn type="button" rounded="true" mdbWavesEffect class="btn-proximax" size="md"
      (click)="printAccountInfo()">
      <span class="color-white">Save Paper Wallet</span>
    </button>

    <button mdbBtn type="button" rounded="true" mdbWavesEffect [disabled]="disabledContinue"
      class="btn-proximax" size="md" [routerLink]="[routeContinue]" >
      <!-- (click)="checkRoute()" -->
      <span class="spinner-border spinner-border-sm text-light mr-sm-2" role="status" aria-hidden="true"
        *ngIf="disabledContinue"></span>
      <span class="color-white">Continue</span>
    </button>
  </div>
</div>
